### ISSUE TITLE
Double bookings

### ISSUE THREAD

**Issue by michaelspooner** [redguava/cliniko-api#108]
Hello,
The API allows multiple bookings of the same time slot for a practitioner. What was the reasoning behind this? Could the appointments API be changed or configured to return an error response/code if the creation of a new appointment conflicts with an existing appointment?

**Comment by JohnColvin** [comment]
Hi Michael,

We don't enforce double bookings because a lot of people that use Clinko double book or overlap appointments. We even have a setting to leave a gap on the calendar so it's easier to schedule a double booking.

After you've created an appointment, you can follow the url provided in the `conflicts` property. That endpoint will tell you if the appointment has a conflict or not.

All the best,
John
