### ISSUE TITLE
Search next_available_time from a specific date

### ISSUE THREAD

**Issue by luizfelipepg** [redguava/cliniko-api#120]
Hi all, I have tried contacting support about the issue I am having and they told me to open an issue about this in here.

I need to call the next_available_time API from a specific date as well as from today.

I know I can use the available_times to specify date range but because your limit is 7 days, if I am looking for something from next monday and the next available time is in 3 months, I will need to call your API several times and this would add latency to my application and more load to your application.

I am just wondering if you could not add a parameter to the next_available_time API where we can specify the starting date.

Thanks in advance,
Luiz

**Comment by jfriedlaender** [comment]
Hi @luizfelipepg,

What is the purpose of starting the search from "next monday"? I ask because already in Cliniko there is a setting that lets the business choose how much "lead time" is required for a booking. It's in the settings > online bookings area within Cliniko. It looks like this...

<img width="632" alt="screenshot 2016-02-26 18 31 21" src="https://cloud.githubusercontent.com/assets/601351/13345964/391a3a1a-dcb7-11e5-8b02-b47f4df72956.png">

The 'next_available_time' in our API respects this setting.

Does that do what you need? Or is there another reason for requiring this.

Joel

**Comment by luizfelipepg** [comment]
I get that but I need sometimes to search from today, sometimes search from next week without UI intervention. 

Imagine this scenario, the practitioner has one appointment this week and one appointments in 3 months. If I search from today I will get this week which is fine. However, if I want to search from next monday, I will also get this weeks appointment.

The only way of fixing that is using the available_times but because of the 7days limit,  I will call your API multiple times until I get the next appointment. It will have an impact on my application as well as yours.

**Comment by luizfelipepg** [comment]
Any updates ?

**Comment by bpinto** [comment]
Hey @luizfelipepg,

it's unlikely that we are going to change this API any time soon, it's very focused on online booking thus being too different from our other API entry points. I suggest you using the [Appointments](https://github.com/redguava/cliniko-api/blob/master/sections/appointments.md) entry point for now and applying your own logic to find the next available slot.
