### ISSUE TITLE
Patient links not return in group appointments

### ISSUE THREAD

**Issue by nasir9bd** [redguava/cliniko-api#136]
**GET /appointments/:Id**

When the appointment type is set to one patient, API returns the patient link. Also patient_name is set. But when it is set for more than one patients, API return no patient links and patient_name is null.

**Comment by JohnColvin** [comment]
Hi Nasir,

I was going to tell you to get the patients via the attendees related to the appointment. However, I see we've neglected to add those to the appointments API response! We should be fixing that up here soon.

Group appointments will not return a patient link or a `patient_name`, since they relate to multiple patients. Both individual and group appointments will have a new link for attendees. An attendee record relates a patient to an appointment.

Thanks for letting us know about this!
