### ISSUE TITLE
Making a request section edit

### ISSUE THREAD

**Issue by akanshmurthy** [redguava/cliniko-api#155]
Issuing an API request with Postman is pretty straightforward with the Basic Auth but the curl request could be made clearer with an actual example with some fake data instead of the placeholder names, as I've seen numerous emails come through the developer's email list with API request failures because of improperly formatted curl requests (I had the same issue when I first tried it too).

**Comment by bpinto** [comment]
I've seen it a few times as well, but usually on some language implementation (PHP, Java, etc.). I'm not sure I understand your idea, is there a snippet or something you could share? Thanks.

**Comment by akanshmurthy** [comment]
I mean just providing a curl sample with actual data (but the data can be fake...).

**Comment by bpinto** [comment]
I see, I think it would be a good addition, but I imagine it wouldn't stop that confusion since we already show the right curl command, we just don't have a publicly available API key.

So your suggestion, is to replace the existing code:

```
curl https://api.cliniko.com/v1/appointments \
  -u API_KEY: \
  -H 'Accept: application/json' \
  -H 'User-Agent: APP_VENDOR_NAME (APP_VENDOR_EMAIL)'
```

with a real data:

```
curl https://api.cliniko.com/v1/appointments \
  -u 12312312312: \
  -H 'Accept: application/json' \
  -H 'User-Agent: my business (my-business@example.com)'
```

and this would return a list of appointments. I think it's a good thing to do, but it's not in our radar at the moment to spend time building this. Hopefully sooner than later.

**Comment by akanshmurthy** [comment]
Yep!

Ok, cool.

**Comment by hagen** [comment]
Closing - as we update sections, I'll start adding in these _semi-real_ examples to make things clearer.
