### ISSUE TITLE
Treatment note HTML tag stripping

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#210]
Tags other than `<div>` `<br>` and `<p>` are stripped from input, and I assume the innerText component of the tag remains? This is all good, except for tags like `<style>`. Tags like `<style>` should be stripped, and their contents removed entirely.
Currently, it appears as though the text inside the `<style>...</style>` tags is retained - which dumps CSS into the treatment note.

Of course, such HTML tags shouldn't be sent in, but it's not always possible to control.

**Comment by JohnColvin** [comment]
You're correct that we keep the content of tags that we strip out. I'm not sure we'll want to have a special case where we strip the entire content for certain tags. I'm leaning toward GIGO on this one.

What's the situation that you can't control where style tags are sent to us?

**Comment by JohnColvin** [comment]
After discussing this with the team, I'm softening to the idea of entirely removing tags like `style` and `script` 😄

**Comment by hagen** [comment]
Lol. I do understand the view that you should leave the inner text of the tag... but tags like `script`, `meta`, `style`, `header` don't even show up in web page rendering, so it seems it'd make sense to always remove those tags *and* their content.
Softie.

**Comment by JohnColvin** [comment]
The winds may have shifted overnight back to GIGO for those tags 😄

We will fix the discrepancy between what's shown in the UI and what we have in the DB, though. It's due to some in motion plans where we changed how the form worked to build the API endpoints and then released it before the views were changed to use the API.

We'll keep you posted 😄
