### ISSUE TITLE
500 error when attempting to create an individual appointment

### ISSUE THREAD

**Issue by jontycg** [redguava/cliniko-api#215]
I'm getting a 500 error when trying to create an individual appointment.

These are the values I'm POSTing to `https://api.cliniko.com/v1/individual_appointments`:

    'starts_at': '2018-03-29T06:35:48.964000+13:00'
    'patient_id': 46782179
    'practitioner_id': 93846
    'appointment_type_id': 269198
    'business_id': 59308

Any help would be much appreciated.

**Comment by hagen** [comment]
Possibly your timestamp Jonty.

Needs to be UTC:
YYYY-MM-DD*T*HH:mm:ss*Z*

Ensure both literal characters T and Z are included, otherwise it'll be
rejected.

Hagen Dittmer
Hello Internets
hagen@hellointernets.com
0417 112 941
Need to tee up a time to meet? Book directly in my Calendar.
<https://hagendittmer.youcanbook.me>

**Comment by Liam-Tait** [comment]
The timestamp seems to accept that format @hagen.

It looks a 500 occurs when a patient_id does not exist. I haven't tested for practitioner_id, appointment_type_id or business_id not existing

A 404 or a helpful error message e.g ('patient does not exist') would be good here.

**Comment by jontycg** [comment]
Cheers @Liam-Tait , looks like that's it. I'll keep the issue open incase the Cliniko team decides to add an error message and fix the 500 error.

**Comment by bpinto** [comment]
You are correct, thanks @Liam-Tait 

We have someone working on this issue already, thanks for the report and the error finding.

**Comment by hagen** [comment]
Closing - resolved.
