### ISSUE TITLE
Why can't treatment_note answers (radios/checks) have `selected: false`?

### ISSUE THREAD

**Issue by hagen** [redguava/cliniko-api#236]
Just noting that when you attempt to create a treatment note section with radio/check answers, and mark the _unselected_ answers `selected: false`, the API errors. I realise marking all non-selected answers `false` is a bit of a tautology, but technically isn't correct. Thoughts? For example, this could be considered a valid treatment note:
```json
{
  "author_name": "Practitioner author",
  "sections": [{
    "name": "Section 1",
    "questions": [
      {
        "name": "Choose just one",
        "type": "radiobuttons",
        "answers": [
          { "value": "Choice 1", "selected": false },
          { "value": "Choice 2", "selected": true },
          { "value": "Choice 3", "selected": false }
        ]
      }
    ]
  }]
}
```
but it will error because of the `selected: false` prop on the answers.

**Comment by JohnColvin** [comment]
This is just a convention that we chose. It makes for one "unselected" state rather than having both the lack of attribute and `selected: false` indicate lack of selection. We could have chosen for the attribute to always be present instead and allow both `true` and `false`, but this ship is already sailing 😓 The only way I see now to support `false` would be to allow both cases and I'm not inclined to do that.

**Comment by bpinto** [comment]
I don't think there is much else to add here. Re-open if necessary.
