### ISSUE TITLE
Adding staging internal admin product integration

### ISSUE THREAD

**Issue by lionsdwarf** [redguava/cliniko-api#281]
Hello,

We would like to white-list one more integration URL for our staging environment. The URL we want to support is https://staging.findoctave.com/cliniko

Please let me know how best to proceed.

Thanks!

**Comment by hagen** [comment]
Hi there - I think instead of adding your staging environments to our production environment (which is what we'd be doing here), you could just test that your staging env works with tests for `https://staging.findoctave.com/cliniko?patient_id={patient_id}`?

i.e. that the request comes from Cliniko itself shouldn't be important; rather that your staging environment correctly responds to requests like that above is the thing you want to check, right?

**Comment by hagen** [comment]
Closing - no reply. Assume all's good 🤙
Re-open if required.
