### ISSUE TITLE
`rescheduled_at` field on appointments?

### ISSUE THREAD

**Issue by craigspaeth** [redguava/cliniko-api#289]
Hello, we'd like to build a feature on Cliniko's API that knows when an appointment is rescheduled. We've tried using `updated_at` but this changes every time a note is added or another property changes—which means we can't rely on it to know _which_ field was updated.

The `cancelled_at` field has worked great for us knowing when an appointment is cancelled, so if there were a `rescheduled_at` field that was filterable as well this would be a wonderful feature to have.

I hope you take this into consideration. Let me know if there's another way to accomplish knowing an appointment was rescheduled via Cliniko's API.

Thanks!

**Comment by hagen** [comment]
Hi @craigspaeth - thanks for the request!

For some context:
`rescheduled_at` might be able to serve your needs, but technically it can't serve the same purpose as `cancelled_at`, because an appointment can be rescheduled more than once. Subsequently, that means `rescheduled_at` can also change, and you'd have no information in the appointment record of how many changes it's been through (which it sounds like you'll need, if we're comparing to `cancelled_at`?)

`cancelled_at` however, doesn't change (once an appointment is cancelled, it can't be _un-cancelled_).

What is your use case here? Knowing _when_ a reschedule happens, or knowing _how many times_ a reschedule has happened?

At this point, you'd probably need to be keeping records of appointments on your side, to then compare the appointment date/times and determine if an appointment has been rescheduled when it has been updated.

Cheers!
