### ISSUE TITLE
Getting information about deleted Appointment Types.

### ISSUE THREAD

**Issue by evorgevol** [redguava/cliniko-api#310]
When calling the appointment api it returns an appointment_type link, if that type is gone then it just returns a 404. Is there any way to get the information for that appointment_type? ie, similar to inactive practitioners endpoint.

Thanks

**Comment by rdrenker** [comment]
Any update on adding this functionality?  

This is particularly problematic when accessing older appointments for which an appointment type is deleted.  Since the `individual_appointments` API call doesn't return any data about the appointment type (other than the ID), it makes it impossible to get this critical information out of Cliniko.

An alternative to adding this functionality would be to add the appointment type name to the `individual_appointments` (which would be far more useful IMHO).

**Comment by bpinto** [comment]
We have released this end point. `/v1/appointment_types/archived`
