### ISSUE TITLE
Endpoint to assist login

### ISSUE THREAD

**Issue by daz-74** [redguava/cliniko-api#53]
I have a request for a new end-point to assist "auto-login".

I am utilising the Cliniko API from within my application, but there are things it can't do, and my user has to log in to their Cliniko account.  As they are already authenticated in my application, I don't want them to have to enter their password again.

Is there some way the api key and user name could be passed through instead of the authenticity token in the login page, so we can force authentication?

Code I have used to do this on other sites is:

```
<html> 
<head> 
<script language="JavaScript" type="text/javascript"> 
function loginForm() { 
document.myform.action = "https://my.cliniko.com/users/sign_in/"; 
document.myform.submit(); 
} 
</script> 
</head> 
<body onload="loginForm()"> 
<form name="myform" method="post"> 
<input type="hidden" name="user[email]" value="[my username]"> 
<input type="hidden" name="user[password]" value="[my password]"> 
</form> 
</body> 
</html>
```

But Cliniko also has an authenticity token preventing this from working.

**Comment by jfriedlaender** [comment]
HI Darryl,

Sorry it's taken so long to finalise this.  Unfortunately we won't be exposing this via the API.

We do not want to have the ability to log into a Cliniko account by using the API key. This is due to security, logging, sessions amongst other things.

I'm going to close this issue, sorry we can't help on this one.

Joel
